export const clients = {
  gsClimatech: {
    name: 'GS Climatech',
    legalName: 'Electricité Plomberie Chauffage - GS Climatech',
    owner: 'Laurent Caillaud',
    address: "44 Rte d'Angers, 49000 Écouflant",
    phone: '+33 6 30 01 38 51',
    phoneDisplay: '06 30 01 38 51',
    founded: 2005,
    rating: 5.0,
    reviews: 209,
    employees: '10-19 salariés',
    services: ['Électricité', 'Plomberie', 'Chauffage', 'Climatisation'],
    zones: ['Angers', 'Écouflant', 'Trélazé', 'Avrillé', 'Saint-Barthélemy', 'Beaucouzé', "Les Ponts-de-Cé"],
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Electricit%C3%A9%20Plomberie%20Chauffage%20-%20GS%20Climatech&query_place_id=ChIJISoHp15P8SkR51uOHCHf_ps',
  },
  h2eau: {
    name: 'H2eau',
    legalName: 'H2eau plomberie - chauffage - dépannage',
    owner: 'Giovanni Vicini',
    address: "71 Rue de l'Étoile, 80090 Amiens",
    phone: '+33 7 45 18 52 82',
    phoneDisplay: '07 45 18 52 82',
    email: 'H2eau.amiens@gmail.com',
    founded: 2023,
    rating: 5.0,
    reviews: 105,
    employees: '1-2 salariés',
    services: ['Recherche de fuite', 'Plomberie', 'Chauffage', 'Climatisation', 'Dépannage 24/7'],
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=H2eau%20plomberie%20Amiens&query_place_id=ChIJt-rfVs8yWQ0RO2Blr81ZA7E',
  },
  urBeroa: {
    name: 'Ur Beroa',
    legalName: 'Ur Beroa - Plombier Bayonne',
    owner: 'Raphael Pacou',
    address: '5 Rue du Canal, 64100 Bayonne',
    phone: '+33 7 86 80 66 42',
    phoneDisplay: '07 86 80 66 42',
    founded: 2015,
    rating: 4.8,
    reviews: 102,
    employees: '1-2 salariés',
    services: ['Plomberie', 'Chauffage', 'Sanitaire', 'Dépannage'],
    zones: ['Bayonne', 'Anglet', 'Biarritz', 'Saint-Jean-de-Luz', 'Hendaye', 'Cambo-les-Bains'],
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Ur%20Beroa%20Raphael%20Pacou%20Plombier%20Bayonne&query_place_id=ChIJQwe73OxAUQ0RFa68cKrPR_s',
  },
  ecochauff: {
    name: 'ÉcoChauff',
    legalName: 'ÉcoChauff - Chauffagiste & Énergies Renouvelables',
    owner: 'Julien Marchand',
    address: '12 Rue de la Transition, 35000 Rennes',
    phone: '+33 6 12 34 56 78',
    phoneDisplay: '06 12 34 56 78',
    email: 'contact@ecochauff.fr',
    founded: 2021,
    rating: 4.9,
    reviews: 87,
    employees: '3-5 salariés',
    services: ['Pompes à chaleur', 'Chaudières biomasse', 'Photovoltaïque', 'Audit énergétique', 'Aides MaPrimeRénov'],
    zones: ['Rennes', 'Cesson-Sévigné', 'Vern-sur-Seiche', 'Chartres-de-Bretagne', 'Bruz', 'Saint-Grégoire'],
    certifications: ['RGE QualiPAC', 'RGE Qualibois', 'Reconnu Garant Environnement'],
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Chauffagiste%20RGE%20Pompe%20%C3%A0%20chaleur%20Rennes',
  },
  maisonpro: {
    name: 'MaisonPro Bati',
    legalName: 'MaisonPro Bati - Entreprise tous corps d\'état',
    owner: 'Stéphane Lefèvre',
    address: '47 Avenue Foch, 49000 Angers',
    phone: '+33 2 41 12 34 56',
    phoneDisplay: '02 41 12 34 56',
    email: 'contact@maisonpro-bati.fr',
    founded: 2008,
    rating: 4.7,
    reviews: 156,
    employees: '20-49 salariés',
    services: ['Plomberie', 'Chauffage', 'Électricité', 'Maçonnerie', 'Couverture', 'Rénovation complète'],
    zones: ['Angers', 'Saint-Barthélemy-d\'Anjou', 'Trélazé', 'Avrillé', 'Beaucouzé', 'Cholet'],
    certifications: ['Qualibat', 'Qualifelec', 'RGE'],
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Entreprise%20b%C3%A2timent%20tous%20corps%20%C3%A9tat%20Angers',
  },
  aquajeune: {
    name: 'Aqua Jeune',
    legalName: 'Aqua Jeune - Plombier moderne',
    owner: 'Maxime Bertrand',
    address: '8 Rue des Cordeliers, 26000 Valence',
    phone: '+33 7 56 78 90 12',
    phoneDisplay: '07 56 78 90 12',
    email: 'maxime@aquajeune.fr',
    founded: 2023,
    rating: 5.0,
    reviews: 64,
    employees: '1-2 salariés',
    services: ['Dépannage rapide', 'Installation sanitaire', 'Recherche de fuite', 'Salle de bain'],
    zones: ['Valence', 'Bourg-lès-Valence', 'Portes-lès-Valence', 'Guilherand-Granges', 'Saint-Péray'],
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Plombier%20moderne%20Valence',
  },
};

export const fakeReviews = {
  gsClimatech: [
    { name: 'Sophie M.', rating: 5, text: "Équipe au top, intervention rapide pour notre chaudière. Laurent et son équipe sont sérieux et travaillent proprement. 20 ans d'expérience, ça se voit.", date: 'il y a 2 semaines' },
    { name: 'Jean-Pierre L.', rating: 5, text: "Installation complète d'une pompe à chaleur. Travail impeccable, conseils précieux et tarif honnête. Je recommande sans hésiter.", date: 'il y a 1 mois' },
    { name: 'Catherine D.', rating: 5, text: "Refait toute la plomberie de la maison. Équipe ponctuelle, respectueuse et compétente. Devis tenu au centime près.", date: 'il y a 1 mois' },
    { name: 'Olivier B.', rating: 5, text: "Une entreprise locale comme on les aime. Réactivité, professionnalisme et finitions soignées. Merci à toute l'équipe.", date: 'il y a 3 mois' },
  ],
  h2eau: [
    { name: 'Marie C.', rating: 5, text: "Fuite enterrée détectée en moins d'une heure. Giovanni est arrivé avec tout le matériel, m'a expliqué le problème simplement. Bluffant.", date: 'il y a 1 semaine' },
    { name: 'Thomas R.', rating: 5, text: "Appelé à 22h pour une fuite, Giovanni était là à 22h45. Pro, rapide, prix juste. Le plombier qu'il faut à Amiens.", date: 'il y a 2 semaines' },
    { name: 'Léa P.', rating: 5, text: "Recherche de fuite sans casse, technologie thermique impressionnante. Pas un coup de marteau, tout réparé en 2h.", date: 'il y a 3 semaines' },
    { name: 'Vincent A.', rating: 5, text: "Service au top, communication parfaite par SMS avant l'arrivée. Giovanni est l'avenir du métier.", date: 'il y a 1 mois' },
  ],
  urBeroa: [
    { name: 'Maialen E.', rating: 5, text: "Raphael est intervenu rapidement pour notre ballon d'eau chaude. Travail soigné, prix raisonnable, et un vrai bayonnais. Milesker !", date: 'il y a 2 semaines' },
    { name: 'Patrick H.', rating: 5, text: "10 ans qu'on fait appel à Ur Beroa pour toute la maison. Toujours impeccable, toujours à l'heure. Un artisan rare.", date: 'il y a 1 mois' },
    { name: 'Amaia D.', rating: 5, text: "Installation d'une nouvelle salle de bain. Conseils précieux, travail propre, délais respectés. Je le recommande à tous mes voisins.", date: 'il y a 2 mois' },
    { name: 'Bernard L.', rating: 4, text: "Très bon plombier, sérieux et honnête. Petit retard sur le rendez-vous mais le travail est nickel.", date: 'il y a 3 mois' },
  ],
  ecochauff: [
    { name: 'Sandrine M.', rating: 5, text: "Installation d'une pompe à chaleur air/eau Atlantic, suivi du dossier MaPrimeRénov complet. Économies de 60% sur la facture de chauffage dès le premier hiver.", date: 'il y a 3 semaines' },
    { name: 'Frédéric L.', rating: 5, text: "Julien a fait un audit énergétique poussé avant les travaux. Devis transparent, aides expliquées clairement, équipe à l'écoute. Je recommande chaudement.", date: 'il y a 1 mois' },
    { name: 'Émilie B.', rating: 5, text: "Pose de panneaux photovoltaïques + ballon thermodynamique. Très bonne coordination avec EDF. Mise en service sans accroc.", date: 'il y a 2 mois' },
    { name: 'Christophe P.', rating: 4, text: "Bon professionnel, sérieux et de bons conseils. Petit retard de chantier dû aux délais de livraison de la PAC, mais le travail est nickel.", date: 'il y a 3 mois' },
  ],
  maisonpro: [
    { name: 'Marie-Claire D.', rating: 5, text: "Rénovation complète d'une maison de 140 m² : maçonnerie, plomberie, électricité, couverture. Un seul interlocuteur, c'est précieux. Chantier livré dans les délais.", date: 'il y a 1 mois' },
    { name: 'Pascal R.', rating: 5, text: "Devis très détaillé, équipe stable et compétente. On a rajouté de l'isolation et un poêle à granulés en cours de chantier, ça s'est fait sans souci.", date: 'il y a 2 mois' },
    { name: 'Nathalie T.', rating: 4, text: "Bon professionnalisme, devis tenu. Communication parfois lente sur les choix de matériaux mais le résultat est très propre.", date: 'il y a 2 mois' },
    { name: 'Bruno A.', rating: 5, text: "Pour une entreprise de cette taille, ils restent humains et accessibles. Stéphane se déplace lui-même pour les devis. Du sérieux.", date: 'il y a 4 mois' },
  ],
  aquajeune: [
    { name: 'Camille H.', rating: 5, text: "Maxime est arrivé en 45 minutes pour une fuite sous l'évier. Tarif annoncé respecté au centime. Je garde son numéro précieusement.", date: 'il y a 1 semaine' },
    { name: 'Romain V.', rating: 5, text: "Refait toute la salle de bain en 5 jours. Photos avant/après dingues, tarifs affichés clairement sur son site, paiement en ligne. C'est ça la modernité.", date: 'il y a 2 semaines' },
    { name: 'Léa F.', rating: 5, text: "Plombier qui répond aux SMS, qui envoie un devis dans la journée, qui arrive à l'heure. Ça paraît normal, mais c'est rare.", date: 'il y a 3 semaines' },
    { name: 'Anthony K.', rating: 5, text: "Tarifs transparents direct sur le site, plus besoin d'appeler trois plombiers pour comparer. Maxime est jeune mais hyper sérieux.", date: 'il y a 1 mois' },
  ],
};
